In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.DataFrame({
    'color':['red','blue','green','green','blue','yellow','blue','yellow']
})
df

    color
0     red
1    blue
2   green
3   green
4    blue
5  yellow
6    blue
7  yellow

In [5]:
# created an instance of OneHotEncoder
encoder=OneHotEncoder()

In [12]:
encoded=encoder.fit_transform(df[['color']]).toarray()  # alphabet wise

In [8]:
import pandas as pd

In [13]:
encoded_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [14]:
encoded_df

   color_blue  color_green  color_red  color_yellow
0         0.0          0.0        1.0           0.0
1         1.0          0.0        0.0           0.0
2         0.0          1.0        0.0           0.0
3         0.0          1.0        0.0           0.0
4         1.0          0.0        0.0           0.0
5         0.0          0.0        0.0           1.0
6         1.0          0.0        0.0           0.0
7         0.0          0.0        0.0           1.0

In [16]:
encoder.transform([['yellow']]).toarray()

C:\Users\DataScience\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 1.]])

In [17]:
pd.concat([df,encoded_df],axis=1)

    color  color_blue  color_green  color_red  color_yellow
0     red         0.0          0.0        1.0           0.0
1    blue         1.0          0.0        0.0           0.0
2   green         0.0          1.0        0.0           0.0
3   green         0.0          1.0        0.0           0.0
4    blue         1.0          0.0        0.0           0.0
5  yellow         0.0          0.0        0.0           1.0
6    blue         1.0          0.0        0.0           0.0
7  yellow         0.0          0.0        0.0           1.0

In [18]:
import seaborn as sns

In [68]:
a=sns.load_dataset('tips')
a
a['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [70]:
encoder_tips=OneHotEncoder()
encoded=encoder_tips.fit_transform(a[['sex']]).toarray()

In [43]:
encoded

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [52]:
sample=pd.DataFrame(encoded,columns=encoder_tips.get_feature_names_out())
sample

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [77]:
encoded=encoder_tips.fit_transform(a[['time']]).toarray()
sample=pd.DataFrame(encoded,columns=encoder_tips.get_feature_names_out())
sample

     time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]