# Pandas Advanced Assessment (25 Questions)

## Setup Cell (Run First)

In [2]:
import pandas as pd

df = pd.DataFrame({
    'Name':['John','Alice','Bob','John','David'],
    'Department':['IT','HR','IT','Sales','HR'],
    'Salary':[50000,60000,70000,55000,65000],
    'Gender':['Male','Female','Male','Male','Female'],
    'Join_Date':['2023-01-10','2022-05-15','2023-03-20','2021-11-05','2022-08-18']
})

df

    Name Department  Salary  Gender   Join_Date
0   John         IT   50000    Male  2023-01-10
1  Alice         HR   60000  Female  2022-05-15
2    Bob         IT   70000    Male  2023-03-20
3   John      Sales   55000    Male  2021-11-05
4  David         HR   65000  Female  2022-08-18

## Section A - value_counts()

Q1. Count employees in each department.

In [10]:
# Write your answer here
print(df.groupby("Department")['Department'].count())
print()
print(df['Department'].value_counts())

Department
HR       2
IT       2
Sales    1
Name: Department, dtype: int64

Department
IT       2
HR       2
Sales    1
Name: count, dtype: int64

Q2. Count employees by gender.

In [9]:
# Write your answer here
print(df.groupby("Gender")['Gender'].count())
print()
print(df['Gender'].value_counts())

Gender
Female    2
Male      3
Name: Gender, dtype: int64

Gender
Male      3
Female    2
Name: count, dtype: int64

Q3. What does df['Department'].value_counts() return?

In [7]:
# Write your answer here
df['Department'].value_counts()

Department
IT       2
HR       2
Sales    1
Name: count, dtype: int64

## Section B - groupby()

Q4. Find average salary by department.

In [12]:
# Write your answer here
df.groupby("Department")['Salary'].mean()

Department
HR       62500.0
IT       60000.0
Sales    55000.0
Name: Salary, dtype: float64

Q5. Find maximum salary by department.

In [13]:
# Write your answer here
df.groupby("Department")['Salary'].max()

Department
HR       60000
IT       50000
Sales    55000
Name: Salary, dtype: int64

Q6. Find minimum salary by department.

In [14]:
# Write your answer here
df.groupby("Department")['Salary'].min()

Department
HR       60000
IT       50000
Sales    55000
Name: Salary, dtype: int64

Q7. Find number of employees in each department.

In [15]:
# Write your answer here
df.groupby("Department")['Department'].count()

Department
HR       2
IT       2
Sales    1
Name: Department, dtype: int64

Q8. What is the purpose of groupby()?

In [ ]:
# Write your answer here
"group the rows based on a column"

## Section C - Aggregations

Q9. Find mean salary.

In [19]:
# Write your answer here
print(df['Salary'].mean())

60000.0

Q10. Find max salary.

In [20]:
# Write your answer here
print(df['Salary'].max())

70000

Q11. Using one statement, find mean, max and min salary by department.

In [22]:
# Write your answer here
df.groupby("Department")["Salary"].agg(["mean","max","min"])

               mean    max    min
Department
HR          62500.0  65000  60000
IT          60000.0  70000  50000
Sales       55000.0  55000  55000

Q12. Difference between mean() and count().

In [ ]:
# Write your answer here
# mean gives the average value 
# count gives the total count of number of values present

## Section D - apply() and map()

Q13. Increase every salary by 10%.

In [24]:
# Write your answer here
df['Salary'].apply(lambda x:x*1.10)

    Name Department  Salary  Gender   Join_Date
0   John         IT   50000    Male  2023-01-10
1  Alice         HR   60000  Female  2022-05-15
2    Bob         IT   70000    Male  2023-03-20
3   John      Sales   55000    Male  2021-11-05
4  David         HR   65000  Female  2022-08-18

Q14. Create Bonus = Salary + 5000 using apply().

In [26]:
# Write your answer here
df['Bonus']=df['Salary'].apply(lambda x:x+5000)

Q15. Convert Male→M and Female→F using map().

In [29]:
# Write your answer here
df['Gender'].map({"Male":"M","Female":"F"})

0    M
1    F
2    M
3    M
4    F
Name: Gender, dtype: object

Q16. Difference between apply() and map().

In [ ]:
# Write your answer here
map: replace the value using a dictionary 
apply : apply a function on to a column

## Section E - String Operations

Q17. Convert all names to uppercase.

In [31]:
# Write your answer here
df['Name'].str.upper()

0     JOHN
1    ALICE
2      BOB
3     JOHN
4    DAVID
Name: Name, dtype: object

Q18. Find names containing letter 'o'.

In [32]:
# Write your answer here
df['Name'].str.contains('o')

0     True
1    False
2     True
3     True
4    False
Name: Name, dtype: bool

Q19. Replace John → J.

In [34]:
# Write your answer here
df['Name'].str.replace("John","J")

0        J
1    Alice
2      Bob
3        J
4    David
Name: Name, dtype: object

## Section F - DateTime

Q20. Convert Join_Date to datetime.

In [40]:
# Write your answer here
df['Join_Date']=pd.to_datetime(df['Join_Date'])
df['Join_Date']

0   2023-01-10
1   2022-05-15
2   2023-03-20
3   2021-11-05
4   2022-08-18
Name: Join_Date, dtype: datetime64[ns]

Q21. Extract year from Join_Date.

In [41]:
# Write your answer here
df['Join_Date'].dt.year

0    2023
1    2022
2    2023
3    2021
4    2022
Name: Join_Date, dtype: int32

Q22. Extract month from Join_Date.

In [47]:
# Write your answer here
df['Join_Date'].dt.month

0     1
1     5
2     3
3    11
4     8
Name: Join_Date, dtype: int32

## Section G - Duplicates

Q23. Find duplicate names.

In [48]:
# Write your answer here
df["Name"].duplicated()

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

Q24. Remove duplicate names.

In [49]:
# Write your answer here
df["Name"].drop_duplicates()

0     John
1    Alice
2      Bob
4    David
Name: Name, dtype: object

## Section H - Pivot Table

Q25. Create a pivot table showing average salary by department.

In [60]:
# Write your answer here
pd.pivot_table(df,values=["Salary"],index="Department",aggfunc="mean")

             Salary
Department
HR          62500.0
IT          60000.0
Sales       55000.0