# Pandas Assessment Notebook (30 Questions)

Covers only the Pandas topics you have revised so far.

## Setup (Run First)

In [1]:
import pandas as pd
import numpy as np

employees_df = pd.DataFrame({
    'EmpID':[101,102,103,104,105],
    'Name':['A','B','C','D','E'],
    'Age':[23,25,np.nan,29,31],
    'Salary':[50000,70000,90000,60000,np.nan],
    'Department':['IT','HR','IT','Sales','HR']
})

sales_df = pd.DataFrame({
    'OrderID':[1,2,3,4],
    'Sales':[1000,1500,1200,1800]
})

bonus_df = pd.DataFrame({
    'EmpID':[101,102,103,106],
    'Bonus':[5000,7000,9000,3000]
})

employees_df

   EmpID Name   Age   Salary Department
0    101    A  23.0  50000.0         IT
1    102    B  25.0  70000.0         HR
2    103    C   NaN  90000.0         IT
3    104    D  29.0  60000.0      Sales
4    105    E  31.0      NaN         HR

## Section A - Series & DataFrame

Q1. Create a Series containing [10,20,30,40].

In [2]:
# Write your answer here
a=pd.Series([10,20,30,40])

Q2. Create a Series with custom index ['a','b','c'] and values [1,2,3].

In [3]:
# Write your answer here
a=pd.Series([1,2,3],index=['a','b','c'])
a

a    1
b    2
c    3
dtype: int64

Q3. Create a DataFrame with columns Name and Age.

In [5]:
# Write your answer here
dic={"Name":['a','b','c','d'],'age':[1,2,3,4]}
a=pd.DataFrame(dic)
a

  Name  age
0    a    1
1    b    2
2    c    3
3    d    4

Q4. What is the difference between Series and DataFrame?

In [6]:
# Write your answer here
# series is 1 dimensional and cannot contain multiple columns
# DataFrame is 2 or more dimensional and can contain multiple dimensions

Q5. Why would you use a custom index?

In [7]:
# Write your answer here
# make data easily readable 
# easily presentable

## Section B - loc & iloc

Q6. Select the Salary column from employees_df.

In [8]:
# Write your answer here

employees_df['Salary']

0    50000.0
1    70000.0
2    90000.0
3    60000.0
4        NaN
Name: Salary, dtype: float64

Q7. Using loc, get the Salary of employee B.

In [13]:
# Write your answer here
employees_df.loc[:,["Salary"]]

    Salary
0  50000.0
1  70000.0
2  90000.0
3  60000.0
4      NaN

Q8. Using iloc, get the Age of the first row.

In [15]:
# Write your answer here
employees_df.iloc[1,2]

np.float64(25.0)

Q9. Using loc, get Name and Salary columns of row index 1.

In [17]:
# Write your answer here
employees_df.loc[1, ["Name","Salary"]]

Name            B
Salary    70000.0
Name: 1, dtype: object

Q10. Explain loc vs iloc.

In [18]:
# Write your answer here
# loc: label based
# iloc: row , column number based

SyntaxError: invalid syntax (1682472580.py, line 2)

## Section C - Arithmetic Operations

Q11. Create a new column Tax = Salary * 0.1.

In [20]:
# Write your answer here
employees_df['Tax']=employees_df['Salary']*0.1
employees_df.head()

   EmpID Name   Age   Salary Department     Tax
0    101    A  23.0  50000.0         IT  5000.0
1    102    B  25.0  70000.0         HR  7000.0
2    103    C   NaN  90000.0         IT  9000.0
3    104    D  29.0  60000.0      Sales  6000.0
4    105    E  31.0      NaN         HR     NaN

Q12. Create a new column NetSalary = Salary - Tax.

In [21]:
# Write your answer here
employees_df['NetSalary']=employees_df['Salary']-employees_df['Tax']
employees_df.head()

   EmpID Name   Age   Salary Department     Tax  NetSalary
0    101    A  23.0  50000.0         IT  5000.0    45000.0
1    102    B  25.0  70000.0         HR  7000.0    63000.0
2    103    C   NaN  90000.0         IT  9000.0    81000.0
3    104    D  29.0  60000.0      Sales  6000.0    54000.0
4    105    E  31.0      NaN         HR     NaN        NaN

Q13. Add a constant bonus of 1000 to Salary.

In [22]:
# Write your answer here
employees_df['Salary']=employees_df['Salary']+1000
employees_df.head()

   EmpID Name   Age   Salary Department     Tax  NetSalary
0    101    A  23.0  51000.0         IT  5000.0    45000.0
1    102    B  25.0  71000.0         HR  7000.0    63000.0
2    103    C   NaN  91000.0         IT  9000.0    81000.0
3    104    D  29.0  61000.0      Sales  6000.0    54000.0
4    105    E  31.0      NaN         HR     NaN        NaN

Q14. Give one real-world use of column multiplication.

In [23]:
# Write your answer here
# example if we we want to to know how much bonus dow the employee gonna earn based on number of years we can multiply no_of_years * percentage per year

Q15. Filter employees with Salary > 60000.

In [24]:
# Write your answer here
employees_df[employees_df['Salary']>60000]

   EmpID Name   Age   Salary Department     Tax  NetSalary
1    102    B  25.0  71000.0         HR  7000.0    63000.0
2    103    C   NaN  91000.0         IT  9000.0    81000.0
3    104    D  29.0  61000.0      Sales  6000.0    54000.0

## Section D - CSV & Inspection

Q16. What does read_csv() do?

In [ ]:
# Write your answer here
# reads data from the csv file

Q17. Explain header vs names.

In [ ]:
# Write your answer here

# header	Specifies which row in the file should be used as the column names.
# names	Assigns custom column names to the DataFrame.

Q18. Explain usecols.

In [ ]:
# Write your answer here
# selects / get columns mentioned in use cols

Q19. Explain skiprows.

In [ ]:
# Write your answer here
# skips the rows count mentioned

Q20. Explain nrows.

In [ ]:
# Write your answer here
# select the num of rows data mentioend here

## Section E - Data Inspection

Q21. Show first 3 rows of employees_df.

In [25]:
# Write your answer here
employees_df[:3]

   EmpID Name   Age   Salary Department     Tax  NetSalary
0    101    A  23.0  51000.0         IT  5000.0    45000.0
1    102    B  25.0  71000.0         HR  7000.0    63000.0
2    103    C   NaN  91000.0         IT  9000.0    81000.0

Q22. Show last 2 rows of employees_df.

In [42]:
# Write your answer here
employees_df[-2:]

   EmpID Name   Age   Salary Department     Tax  NetSalary
3    104    D  29.0  61000.0      Sales  6000.0    54000.0
4    105    E  31.0      NaN         HR     NaN        NaN

Q23. Generate summary statistics.

In [43]:
# Write your answer here
employees_df.describe()

            EmpID        Age        Salary          Tax     NetSalary
count    5.000000   4.000000      4.000000     4.000000      4.000000
mean   103.000000  27.000000  68500.000000  6750.000000  60750.000000
std      1.581139   3.651484  17078.251277  1707.825128  15370.426149
min    101.000000  23.000000  51000.000000  5000.000000  45000.000000
25%    102.000000  24.500000  58500.000000  5750.000000  51750.000000
50%    103.000000  27.000000  66000.000000  6500.000000  58500.000000
75%    104.000000  29.500000  76000.000000  7500.000000  67500.000000
max    105.000000  31.000000  91000.000000  9000.000000  81000.000000

Q24. Convert employees_df to NumPy array.

In [44]:
# Write your answer here
employees_df.to_numpy()

array([[101, 'A', 23.0, 51000.0, 'IT', 5000.0, 45000.0],
       [102, 'B', 25.0, 71000.0, 'HR', 7000.0, 63000.0],
       [103, 'C', nan, 91000.0, 'IT', 9000.0, 81000.0],
       [104, 'D', 29.0, 61000.0, 'Sales', 6000.0, 54000.0],
       [105, 'E', 31.0, nan, 'HR', nan, nan]], dtype=object)

Q25. Sort employees_df by index descending.

In [45]:
# Write your answer here
employees_df.sort_index(axis=0,ascending=False)

   EmpID Name   Age   Salary Department     Tax  NetSalary
4    105    E  31.0      NaN         HR     NaN        NaN
3    104    D  29.0  61000.0      Sales  6000.0    54000.0
2    103    C   NaN  91000.0         IT  9000.0    81000.0
1    102    B  25.0  71000.0         HR  7000.0    63000.0
0    101    A  23.0  51000.0         IT  5000.0    45000.0

## Section F - Missing Values

Q26. Find missing values in employees_df.

In [46]:
# Write your answer here
employees_df.isna()

   EmpID   Name    Age  Salary  Department    Tax  NetSalary
0  False  False  False   False       False  False      False
1  False  False  False   False       False  False      False
2  False  False   True   False       False  False      False
3  False  False  False   False       False  False      False
4  False  False  False    True       False   True       True

Q27. Remove rows with missing values.

In [47]:
# Write your answer here
employees_df.dropna()

   EmpID Name   Age   Salary Department     Tax  NetSalary
0    101    A  23.0  51000.0         IT  5000.0    45000.0
1    102    B  25.0  71000.0         HR  7000.0    63000.0
3    104    D  29.0  61000.0      Sales  6000.0    54000.0

Q28. Fill missing Age with 0.

In [48]:
# Write your answer here
employees_df.fillna({'Age':0})

   EmpID Name   Age   Salary Department     Tax  NetSalary
0    101    A  23.0  51000.0         IT  5000.0    45000.0
1    102    B  25.0  71000.0         HR  7000.0    63000.0
2    103    C   0.0  91000.0         IT  9000.0    81000.0
3    104    D  29.0  61000.0      Sales  6000.0    54000.0
4    105    E  31.0      NaN         HR     NaN        NaN

Q29. Explain ffill vs bfill.

In [ ]:
# ffill (Forward Fill)
# Copies the PREVIOUS non-null value forward

# bfill (Backward Fill)
# Copies the NEXT non-null value backward

Q30. When would you use interpolate()?

In [ ]:
# Write your answer here

# Interpolation is used to estimate missing values based on surrounding data, instead of simply copying previous or next values.

## Bonus Practice - Merge / Join / Concat (Optional)

Merge employees_df and bonus_df on EmpID.

In [ ]:
# Write your answer here

Concatenate employees_df with a copy of itself.

In [ ]:
# Write your answer here

Join two DataFrames using index.

In [ ]:
# Write your answer here

# Self Evaluation

| Topic | Score |
|--------|--------|
| Series & DataFrame | /5 |
| loc & iloc | /5 |
| Arithmetic Operations | /5 |
| CSV & Inspection | /5 |
| Data Inspection | /5 |
| Missing Values | /5 |

**Total: /30**