In [12]:
import pandas as pd

In [14]:
x=[3,4,5,6,7,8]
var = pd.Series(x)

In [15]:
var

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [16]:
dic={'name':[1,2,3,4,5,6,7],'age':[1,1,1,1,1,1,1,1,1,1,1,1] }
var_1 = pd.Series(dic)
var_1

name                   [1, 2, 3, 4, 5, 6, 7]
age     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
dtype: object

In [18]:
# creating a dic with same value and different index 

a=pd.Series(12,index=[1,2,3,4,5,6])
a

1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64

In [19]:
b=pd.Series([1,2,3,4,5,6],dtype='float',name='python')

In [20]:
b

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
Name: python, dtype: float64

In [22]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([1,2,3,4,5,6])
s1+s2

0    2.0
1    4.0
2    6.0
3    8.0
4    NaN
5    NaN
dtype: float64

In [23]:
# DataFrames 
l=[1,2,3,4,5,6]
a=pd.DataFrame(l)
print(a)

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [32]:
d={'a':[1,2,3,4,5],'b':[6,7,8,9,10],'c':[11,12,13,14,15]}
var=pd.DataFrame(d,columns=["b","c"],index=['a','e','i','o','u'])
var

    b   c
a   6  11
e   7  12
i   8  13
o   9  14
u  10  15

In [33]:
# accessing elements 

var ['b']['a'] # column row

np.int64(6)

In [34]:
list_1 =[[1,2,3,4,5],[6,7,8,9]]
a=pd.DataFrame(list_1)
print(a)

   0  1  2  3    4
0  1  2  3  4  5.0
1  6  7  8  9  NaN

In [39]:
dic={'s':pd.Series([1,2,3,4,5,6]),'t':pd.Series([7,8,9,10,11])}
a=pd.DataFrame(dic)
a

   s     t
0  1   7.0
1  2   8.0
2  3   9.0
3  4  10.0
4  5  11.0
5  6   NaN

### Arthematic Operations

In [46]:
dic={'a':[1,2,3,4,5],'b':[6,7,8,9,10]}
a=pd.DataFrame(dic)
a['c']=a['a']+a['b']
a['d']=a['a']-a['b']
a['e']=a['a']*a['b']
a['f']=a['a']/a['b']
a['g']=a['a']//a['b']
a['g']=a['a']**a['a']
print(a)

   a   b   c  d   e         f     g
0  1   6   7 -5   6  0.166667     1
1  2   7   9 -5  14  0.285714     4
2  3   8  11 -5  24  0.375000    27
3  4   9  13 -5  36  0.444444   256
4  5  10  15 -5  50  0.500000  3125

## Delete and Insert Data

In [48]:
dic={'A':[1,2,3,4,5],'B':[6,7,8,9,10]}
a=pd.DataFrame(dic)
a

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [51]:
a.insert(2,'c',[0,0,0,0,0]) # ( POS,INDEX,VALUES)

In [53]:
a

   A   B  c
0  1   6  0
1  2   7  0
2  3   8  0
3  4   9  0
4  5  10  0

In [54]:
# COPYING FROM EXISTING 
a['d']=a['A'][:3]
print(a)

   A   B  c    d
0  1   6  0  1.0
1  2   7  0  2.0
2  3   8  0  3.0
3  4   9  0  NaN
4  5  10  0  NaN

In [55]:
# deleting data 
a.pop('d')
print(a)

   A   B  c
0  1   6  0
1  2   7  0
2  3   8  0
3  4   9  0
4  5  10  0

## Write to CSV

In [63]:
df=pd.DataFrame({'a':[1,2,3,4,5,6],'b':[5,6,7,8,9,10]})
print(df)

   a   b
0  1   5
1  2   6
2  3   7
3  4   8
4  5   9
5  6  10

In [64]:
df.insert(2,'c',[1,1,1,1,1,1])
print(df)

   a   b  c
0  1   5  1
1  2   6  1
2  3   7  1
3  4   8  1
4  5   9  1
5  6  10  1

In [65]:
df.to_csv('newSample.csv')# creating a csv
df.to_csv('newSample.csv',index=False)# without default index
df.to_csv('newSample.csv',index=False,header=[1,2,3]) # with custom index